### PR TITLE
Build on ppc64(le), s390x

### PR DESCRIPTION
**Pull request by sul3n3t**
These stubs will allow compilation on ppc64, ppc64le, and s390x architectures.

### CODE REVIEW

**Comment by sul3n3t** [comment]
@stevvooe PTAL

**Comment by stevvooe** [comment]
LGTM

These probably need support. cc @estesp

**Comment by sul3n3t** [comment]
Thanks @stevvooe! Do you think this is mergeable or would you like to wait on @estesp feedback?

**Comment by stevvooe** [comment]
@sul3n3t I'd like to get a little feedback to know if we need particular "road map" issues.

**Comment by estesp** [comment]
A quick spot check seems to show these syscalls (the xattr family of calls) are available in current Golang implementation for ppc64le and s390x (for example: [https://github.com/golang/go/blob/master/src/syscall/zsyscall_linux_ppc64le.go](https://github.com/golang/go/blob/master/src/syscall/zsyscall_linux_ppc64le.go))

So; obviously this PR is one way to get a building project for those architectures, but seems the long term solution is an update to the generate scripts to add the pairs for `GOARCH`/`GOOS` to get actual proper generation for these syscalls.

**Pull request merged**
