### PR TITLE
CAS representation for alternative data stream

### LINKED ISSUE #47: [Suggestion] CAS representation for alternative data stream
```pb
message Resource {
  ..
  // Ads stores one or more alternate data streams for the target resource.
  map<string, bytes> ads = 13;
}
```

In current design, the representation of ADS is likely to become so huge, because it contains the full data of ADS.

So WDYT about adding CAS representation for ADS?
i.e.
```pb
message Resource {
  ..
  // Ads stores one or more alternate data streams for the target resource.
  map<string, bytes> ads = 13;
  // AdsDigests stores digests of one or more alternate data streams for the target resource.
  // How to access the actual data using the digest is not defined.
  // Intersection of Ads and AdsDigests SHOULD be an empty set.
  map<string, string> ads_digests = 14;
}
```

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Fix #47 

Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>

### CODE REVIEW

**Comment by stevvooe** [comment]
LGTM

Does this need code to handle extraction and application?

**Comment by dmcgowan** [comment]
LGTM

**Comment by AkihiroSuda** [comment]
@stevvooe 
Yes, but I think we can defer implementation until someone needs this

**Comment by stevvooe** [comment]
@AkihiroSuda Agreed!

**Pull request merged**
